version: "3.0"

services:
  data-migration:
    container_name: data-migration
    build:
      context: ../
      dockerfile: ./data-migration/dockerfile
    image: rsd/data-migration:0.0.8
    # environment:
    #   PROPERTIES: "/usr/mymaven/.env.production.local"
    env_file:
      # use main env file
      - ../.env
    network_mode: "host"
