version: "3.0"

services:
  database:
    container_name: database
    build: ./database
    image: rsd/database:0.0.11
    ports:
    # enable connection from outside
     - "5432:5432"
    env_file:
      - .env.production
    volumes:
      # persist data in named docker volume
      # to remove use: docker-compose down --volumes
      # to inspect use: docker volume ls
      - pgdb:/var/lib/postgresql/data/
    networks:
      - net

  backend:
    container_name: backend
    build: ./backend-postgrest
    image: rsd/backend-postgrest:0.0.1
    expose:
      - 3500
    env_file:
      - .env.production
    depends_on:
      - "database"
    networks:
      - net

  auth:
    container_name: auth
    build:
      context: .
      dockerfile: ./authentication/dockerfile
    image: rsd/auth:0.0.5
    expose:
      - 7000
    # NOTE! update to use env_file
    # environment:
    #   PROPERTIES: "/usr/mymaven/.env.production"
    env_file:
      - .env.production
    depends_on:
      - "database"
      - "backend"
    networks:
      - net

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      # dockerfile to use for build
      dockerfile: Dockerfile
    # update version number to corespond to frontend/package.json
    image: rsd/frontend:0.5.8
    env_file:
      - .env.production
    expose:
      - 3000
    depends_on:
      - "database"
      - "backend"
      - "auth"
    networks:
      - net

  nginx:
    container_name: nginx
    build:
      context: ./nginx
    image: rsd/nginx:0.0.2
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - "database"
      - "backend"
      - "auth"
      - "frontend"
    networks:
      - net

  scrapers:
    container_name: scrapers
    build: ./scrapers
    image: rsd/scrapers:0.0.3
    env_file:
      - .env.production
    depends_on:
      - "database"
      - "backend"
    networks:
      - net

# define name for docker network
# it should have name: rsd-as-a-service_net
networks:
  net:

# named volumes can be managed easier using docker-compose
# volume should have name rsd-as-a-service_pgdb
volumes:
  pgdb:
