
name: docker build scrapers

on:
  push:
    branches:
      - release
    paths:
      - "scrapers/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "get-npm-version"
        id: package-version-rsd
        uses: martinbeentjes/npm-get-version-action@master
        with:
          path: deployment
      - name: "build the scrapers docker image"
        run: |
          IMAGE_TAG=ghcr.io/research-software-directory/rsd-saas/scrapers
          echo image_tag $IMAGE_TAG
          IMAGE_TAG_RSD=ghcr.io/research-software-directory/rsd-saas/scrapers:${{steps.package-version-rsd.outputs.current-version}}
          echo image_tag_rsd $IMAGE_TAG_RSD
          docker build -t $IMAGE_TAG_RSD -t $IMAGE_TAG -f scrapers/dockerfile ./scrapers
      - name: "login to ghcr"
        run: echo "${{secrets.GITHUB_TOKEN}}" | docker login https://ghcr.io -u ${{github.actor}} --password-stdin
      - name: "push image to ghcr"
        run: |
          echo push scrapers image with all tags
          docker push ghcr.io/research-software-directory/rsd-saas/scrapers --all-tags


