
name: docker build frontend

on:
  push:
    branches:
      - frontend
    paths:
      - "frontend/**"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "get-npm-version-frontend"
        id: package-version-frontend
        uses: martinbeentjes/npm-get-version-action@master
        with:
          path: frontend
      - name: conventional changelog
        id: changelog
        # https://github.com/TriPSs/conventional-changelog-action
        uses: TriPSs/conventional-changelog-action@latest
        with:
          # you can also create separate token to trace action
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          version-file: "./deployment/package.json"

      - name: "build frontend image"
        if: ${{steps.changelog.outputs.skipped == 'false'}}
        run: |
          IMAGE_TAG=ghcr.io/research-software-directory/rsd-saas/frontend
          echo image_tag $IMAGE_TAG
          IMAGE_TAG_RSD=ghcr.io/research-software-directory/rsd-saas/frontend:${{steps.changelog.outputs.tag}}
          echo image_tag_rsd $IMAGE_TAG_RSD
          IMAGE_TAG_FE=ghcr.io/research-software-directory/rsd-saas/frontend:${{steps.package-version-frontend.outputs.current-version}}
          echo image_tag_fe $IMAGE_TAG_FE
          docker build -t $IMAGE_TAG_RSD -t $IMAGE_TAG_FE -t $IMAGE_TAG -f frontend/Dockerfile ./frontend
      - name: "login to ghcr"
        run: echo "${{secrets.GITHUB_TOKEN}}" | docker login https://ghcr.io -u ${{github.actor}} --password-stdin
      - name: "push image to ghcr"
        run: |
          echo push frontend image with all tags
          docker push ghcr.io/research-software-directory/rsd-saas/frontend --all-tags

      

