FROM maven:3.8.3-openjdk-17
WORKDIR /usr/mymaven
RUN mkdir --parents ./src/main
COPY authentication/pom.xml .
RUN mvn clean package -Dmaven.main.skip -Dmaven.test.skip && rm -r ./target && mvn exec:java --fail-never
COPY authentication/src/main ./src/main
# COPY .env.production .
RUN mvn compile
CMD mvn exec:java -Dexec.args=$PROPERTIES